config/routes.rb
Rails.application.routes.draw do

  resources :videos
  resources :biodata
  resources :notification_data
  resources :testimonies
  resources :detail_motivators
  resources :schedules
  mount Ckeditor::Engine => '/ckeditor'
  get 'dashboard/index'
  get 'dashboard' => "dashboard#index", as: :dashboard
  get 'dashboard/partial_conver'
  get 'dashboard/partial_msgbox'
  get 'dashboard/partial_notif'
  get 'users/message_box'
  get 'messages/partial_conver'
  get 'pages/partial_conver'
  resources :messages


  root 'pages#index'

  resources :packages
  resources :conversations
  resources :before_conversation
  resources :before_box
  resources :after_register
  resources :promos
  resources :articles
  resources :article_categories, path: "kategori"
  resources :quotes
  resources :images
  resources :sliders
  resources :message_boxes
  resources :problem_categories
  resources :users
  get '/answer' => "pages#answer", as: :answer
  get '/answer-chat' => "pages#answer_chat", as: :answer_chat
  get '/rate-box' => "pages#rate_box", as: :rate_box
  get '/list_box' => "pages#list_box", as: :list_box
  get '/list_chat' => "pages#list_chat", as: :list_chat
  get '/user_agrement' => "pages#user_agrement", as: :user_agrement
  get '/intro' => "pages#intro", as: :intro
  get '/questioner' => "pages#questioner", as: :questioner
  get '/code-of-conduct' => "pages#conduct", as: :conduct
  get '/setup-payment' => "payments#init_payment", as: :init_payment
  get '/detail-payment' => "pages#payment", as: :payment_detail
  get '/beli-paket' => "conversations#init_conversation", as: :init_conversation
  get '/finish' => "conversations#finish", as: :finish
  get '/list-paket' => "pages#list_package", as: :list_package
  get '/about' => "pages#about", as: :about
  get '/contact' => "pages#contact", as: :contact
  get '/history' => "pages#history", as: :history
  get '/history-mtv' => "pages#history_mtv", as: :history_mtv
  get 'list-province' =>  "shared#province"
  get 'list-city' =>  "shared#city"
  get 'list-category' =>  "shared#problem_category"
  get 'validate_promo_code' => "payments#validate_promo_code"
  get '/payment-success' => "payments#payment_success"
  get '/payment-pending' => "payments#payment_pending"
  get '/payment-error' => "payments#payment_error"
  get 'init_box' => "message_boxes#init_box", as: :init_box
  get 'finish_box' => "pages#finish", as: :finish_message_box
  get 'info-motivator' => "pages#mtv_info", as: :mtv_info
  post 'payments/notify'

  get "/faq" => "dashboard#faq", :as => :faq
  get "/semua-artikel" => "pages#allstory", :as => :allstory
  post "/sendkeys" => "message_boxes#getJSON", :as => :getJSON
   post "/sendNo" => "message_boxes#sendPush", :as => :sendPush
  resources :payments
  devise_for :users ,
   path: '',
   path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, :controllers => { :sessions => "sessions" }

   namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        delete "log_out", to: "sessions#destroy"
      end
        put "update_identity", to: "users#update_identity"
        resources :message_boxes
        put "add_rating/:id", to: "message_boxes#create_rating"
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout :determine_layout
  def index
    if current_user.is_admin? || current_user.is_human_capital? || current_user.is_motivator? || current_user.is_finance?
      @all_client = User.client
      @new_client = User.client.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month)
      @message_box = MessageBox.where.not(message: "")
      @message_box_unread = MessageBox.where(status: "init")
      @message_box_process = MessageBox.where(status: "motivator-selected").where.not(problem_category_id: "").where.not(message: "").where.not(question_1: "").where.not(message: "").where.not(question_2: "")
      @message_box_process = MessageBox.where(status: "finish").where.not(problem_category_id: "").where.not(message: "").where.not(question_1: "").where.not(message: "").where.not(question_2: "")
      @user_from_mkt =  @new_client.where(signup_referral_code: ["MKT-01", "MKT-02","MKT-03" "MKT-04", "MKT-05", "MKT-06"]).count
      @user_from_dkt = @new_client.where(signup_referral_code: ["DKT-01", "DKT-02","DKT-03" "DKT-04", "DKT-05", "DKT-06"]).count
      @user_direct = @new_client.where.not(signup_referral_code: ["DKT-01", "DKT-02","DKT-03" "DKT-04", "DKT-05", "DKT-06","MKT-01", "MKT-02","MKT-03" "MKT-04", "MKT-05", "MKT-06"]).count
      @conversation = Conversation.where.not(problem_category_id: nil).where.not(status: ["motivator-selected","motivator-reply","finish"])
      @users = User.motivator
    end
    if current_user.is_motivator?
      @message_box_unread = MessageBox.where(status:'motivator-selected').where(motivator_id: current_user.id)
      @all_conversation = Conversation.where(motivator_id: current_user.id)
      @conversation = Conversation.where(motivator_id: current_user.id).where.not(status: 'finish')

      @notif_msg_box = MessageBox.where(motivator_id: current_user.id).where.not(status: ["finish", "rated"]).count
      @notif_lv_chat = Conversation.where(motivator_id: current_user.id).where.not(status: ["finish", "rated"]).count
    end
    if current_user.is_client?
      unless current_user.identity_complete?
        redirect_to questioner_path
      end
    end

  end
    def partial_conver
      if current_user.is_admin? || current_user.is_human_capital? || current_user.is_motivator? || current_user.is_finance?
        @all_client = User.client
        @new_client = User.client.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month)
        @message_box = MessageBox.where.not(message: "").where.not(problem_category_id: "").where.not(question_1: "").where.not(message: "").where.not(question_2: "")
        @message_box_unread = MessageBox.where(status: "init").where.not(problem_category_id:"").where.not(message: "").where.not(question_1: "").where.not(message: "").where.not(question_2: "")
        @message_box_process = MessageBox.where(status: "motivator-selected").where.not(problem_category_id: "").where.not(message: "").where.not(question_1: "").where.not(message: "").where.not(question_2: "")
        @message_box_process = MessageBox.where(status: "finish").where.not(problem_category_id: "").where.not(message: "").where.not(question_1: "").where.not(message: "").where.not(question_2: "")
        @user_from_mkt =  @new_client.where(signup_referral_code: ["MKT-01", "MKT-02","MKT-03" "MKT-04", "MKT-05", "MKT-06"]).count
        @user_from_dkt = @new_client.where(signup_referral_code: ["DKT-01", "DKT-02","DKT-03" "DKT-04", "DKT-05", "DKT-06"]).count
        @user_direct = @new_client.where.not(signup_referral_code: ["DKT-01", "DKT-02","DKT-03" "DKT-04", "DKT-05", "DKT-06","MKT-01", "MKT-02","MKT-03" "MKT-04", "MKT-05", "MKT-06"]).count
      @conversation = Conversation.where.not(problem_category_id: nil).where.not(status: ["motivator-selected","motivator-reply","finish","rated"])
      end
      if current_user.is_motivator?
        @message_box_unread = MessageBox.where(status:'motivator-selected').where(motivator_id: current_user.id)
        @all_conversation = Conversation.where(motivator_id: current_user.id)
        @conversation = Conversation.where(motivator_id: current_user.id).where.not(status: 'finish')
      end
      render :partial => "dashboard/list_conversation"
    end
    def partial_msgbox

      render :partial => "dashboard/list_msgbox"
    end

    def partial_notif

      render :partial => "dashboard/list_notif"
    end

    def sendPush
		notif_data = NotificationDatum.create(endpoint: params[:subscription][:endpoint],
		                        p256dh_key: params[:subscription][:keys][:p256dh],
		                        auth_key: params[:subscription][:keys][:auth])

		user = current_user.update_attributes(auth_key: params[:subscription][:keys][:auth], :notif_id => notif_data.id)
    user = current_user
		sendPayload(user)
		render body: ""
	end



    private
    def determine_layout
      if current_user.is_client? || current_user.is_motivator?
        "application"
      else
        "admin"
      end
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_dsb_client.html.erb
<section class="d-none d-md-block" style="min-height:67vh">
  <div class="container">
    <div class="row">
      <div class="col-md-3">

        <% if current_user.messeage_boxs_client.count == 0 %>
        <a href="<%= init_box_path %>">
          <div class="text-center">
            <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Box Uneg Uneg</h3>
            </div >
          </a>
        <% else %>
        <% if current_user.messeage_boxs_client.last.status.to_s == "finish" || current_user.messeage_boxs_client.last.status.to_s == "init" %>
        <a href="<%= list_box_path %>">
        <div class="text-center">
          <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
          <h3 class="text-blue-dark">Box Uneg Uneg</h3>
        </div>
        </a>
        <% else %>
        <% if current_user.messeage_boxs_client.last.status == "rated" %>
        <a href="<%= init_box_path %>">
          <div class="text-center">
            <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Box Uneg Uneg</h3>
            </div >
          </a>
        <% else %>

        <a href="<%= before_box_path(:question_1) %>">
          <div class="text-center">
            <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Box Uneg Uneg</h3>
          </div>
        </a>
        <% end %>
        <% end %>
        <% end %>
      </div>
      <div class="col-md-3">
        <% if current_user.conversations.count == 0 %>
        <a href="<%= init_conversation_path %>">
          <div class="text-center">
            <img src="<%= asset_url('chat.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Chat</h3>
          </div>
        </a>
        <% else %>
        <% if current_user.conversations.last.status == "finish"  || current_user.conversations.last.status == "client-reply" || current_user.conversations.last.status == "motivator-reply" %>
        <a href="<%= messages_path %>">
          <div class="text-center">
            <img src="<%= asset_url('chat.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Chat</h3>
          </div>
        </a>
          <% else %>
          <a href="<%= init_conversation_path %>">
            <div class="text-center">
              <img src="<%= asset_url('chat.png') %>" alt="" class="w-100 mb-3 hvr-grow">
              <h3 class="text-blue-dark">Chat</h3>
            </div>
          </a>
        <% end %>


        <% end %>
        </div>
      <div class="col-md-3">
        <a href="<%= mtv_info_path %>">
          <div class="text-center">
            <img src="<%= asset_url('info-motivator.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Info Motivator</h3>
          </div>
        </a>
      </div>
      <div class="col-md-3">
        <a href="<%= history_path %>">
          <div class="text-center">
            <img src="<%= asset_url('history.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">History</h3>
          </div>
        </a>
      </div>
    </div>
  </div>
</section>

<section class="d-block d-sm-none">
  <div class="container">
    <div class="owl-carousel dashboard-slider owl-theme">
    <div class="col-md-12">
              <% if current_user.messeage_boxs_client.count == 0 %>
              <a href="<%= init_box_path %>">
                <div class="text-center">
                  <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
                  <h3 class="text-blue-dark">Box Uneg Uneg</h3>
                  </div >
                </a>
              <% else %>
              <% if current_user.messeage_boxs_client.last.status.to_s == "finish" || current_user.messeage_boxs_client.last.status.to_s == "init" %>
              <a href="<%= list_box_path %>">
              <div class="text-center">
                <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
                <h3 class="text-blue-dark">Box Uneg Uneg</h3>
              </div>
              </a>
              <% else %>
              <% if current_user.messeage_boxs_client.last.status == "rated" %>
              <a href="<%= init_box_path %>">
                <div class="text-center">
                  <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
                  <h3 class="text-blue-dark">Box Uneg Uneg</h3>
                  </div >
                </a>
              <% else %>

              <a href="<%= before_box_path(:question_1) %>">
                <div class="text-center">
                  <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
                  <h3 class="text-blue-dark">Box Uneg Uneg</h3>
                </div>
              </a>
              <% end %>
              <% end %>
              <% end %>
            </div>
      <div class="col-md-12">
        <% if  current_user.conversations.count ==0 %>
        <a href="<%= init_conversation_path %>">
          <div class="text-center">
            <img src="<%= asset_url('chat.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Chat</h3>
          </div>
        </a>
          <% else %>
          <% if current_user.conversations.last.status == "finish" || current_user.conversations.last.status == "rated" || current_user.conversations.last.status == "client-reply" || current_user.conversations.last.status == "motivator-reply" %>
          <a href="<%= init_conversation_path %>">
            <div class="text-center">
              <img src="<%= asset_url('chat.png') %>" alt="" class="w-100 mb-3 hvr-grow">
              <h3 class="text-blue-dark">Chat</h3>
            </div>
          </a>
            <% else %>

          <a href="<%= messages_path %>">
            <div class="text-center">
              <img src="<%= asset_url('chat.png') %>" alt="" class="w-100 mb-3 hvr-grow">
              <h3 class="text-blue-dark">Chat</h3>
            </div>
          </a>
        <% end %>


        <% end %>

      </div>
      <div class="col-md-12">
        <a href="<%= mtv_info_path %>">
          <div class="text-center">
            <img src="<%= asset_url('info-motivator.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Info Motivator</h3>
          </div>
        </a>
      </div>
      <div class="col-md-12">
        <a href="<%= history_path %>">
          <div class="text-center">
            <img src="<%= asset_url('history.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">History</h3>
          </div>
        </a>
      </div>
    </div>

  </div>
</section>

app/views/dashboard/_dsb_mtv.html.erb
<section class="d-none d-md-block">
  <div class="container">
    <div class="row">
      <div class="col-md-3 position-relative">
        <% unless @notif_msg_box == 0 %>
        <div class="position-absolute d-flex align-items-center justify-content-center" style="height:50px;width:50px;background-color:#65c8d0;padding:5px;color:white;border-radius:50%;z-index:2;">
          <span><strong><%= @notif_msg_box.to_i %></strong></span>
        </div>
        <% end %>

        <a href="<%= list_box_path %>">
          <div class="text-center">
            <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Box Uneg Uneg</h3>
          </div>
        </a>
      </div>
      <div class="col-md-3 position-relative">
        <% unless @notif_lv_chat == 0 %>
        <div class="position-absolute d-flex align-items-center justify-content-center" style="height:50px;width:50px;background-color:#65c8d0;padding:5px;color:white;border-radius:50%;z-index:2;">
          <span><strong><%= @notif_lv_chat.to_i %></strong></span>
        </div>
        <% end %>
        <a href="<%= list_chat_path %>">
          <div class="text-center">
            <img src="<%= asset_url('chat.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Chat</h3>
          </div>
        </a>
      </div>

      <div class="col-md-3">
        <a href="<%= mtv_info_path %>">
          <div class="text-center">
            <img src="<%= asset_url('info-motivator.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Info Motivator</h3>
          </div>
        </a>
      </div>
      <div class="col-md-3">
        <a href="<%= history_mtv_path %>">
          <div class="text-center">
            <img src="<%= asset_url('history.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">History</h3>
          </div>
        </a>
      </div>

    </div>
  </div>
</section>

<section class="d-block d-sm-none">
  <div class="container">
    <div class="owl-carousel dashboard-slider owl-theme">
      <div class="col-md-12 position-relative">
        <% unless @notif_msg_box == 0 %>
        <div class="position-absolute d-flex align-items-center justify-content-center" style="height:50px;width:50px;background-color:#65c8d0;padding:5px;color:white;border-radius:50%;z-index:2;">
          <span><strong><%= @notif_msg_box.to_i %></strong></span>
        </div>
        <% end %>
        <a href="<%= list_box_path %>">
          <div class="text-center">
            <img src="<%= asset_url('box.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Box Uneg Uneg</h3>
          </div>
        </a>
      </div>
      <div class="col-md-12 position-relative">
        <% unless @notif_lv_chat == 0 %>
        <div class="position-absolute d-flex align-items-center justify-content-center" style="height:50px;width:50px;background-color:#65c8d0;padding:5px;color:white;border-radius:50%;z-index:2;">
          <span><strong><%= @notif_lv_chat.to_i %></strong></span>
        </div>
        <% end %>
        <div class="col-md-3">
          <a href="<%= list_chat_path %>">
            <div class="text-center">
              <img src="<%= asset_url('chat.png') %>" alt="" class="w-100 mb-3 hvr-grow">
              <h3 class="text-blue-dark">Chat</h3>
            </div>
          </a>
        </div>
      </div>
      <div class="col-md-12">
        <a href="<%= mtv_info_path %>">
          <div class="text-center">
            <img src="<%= asset_url('info-motivator.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">Info Motivator</h3>
          </div>
        </a>
      </div>
      <div class="col-md-12">
        <a href="<%= history_mtv_path %>">
          <div class="text-center">
            <img src="<%= asset_url('history.png') %>" alt="" class="w-100 mb-3 hvr-grow">
            <h3 class="text-blue-dark">History</h3>
          </div>
        </a>
      </div>
    </div>

  </div>
</section>

app/views/dashboard/_list_conversation.html.erb
<% @conversation.each do |x| %>
<tr>
  <td class="txt-oflo"><%= x.user.full_name %></td>
  <td class="txt-oflo"><%= x.created_at.strftime('%d-%m-%Y  %T ') %></td>
  <td class="txt-oflo"><%= x.problem_category.name rescue"" %></td>
  <td class="txt-oflo"><%= x.motivator.motivator_code rescue "belum ada motivator" %></td>

  <td class="txt-oflo">
    <span class="badge badge-danger">
      <% if x.status == "init" %>
      BELUM ADA MOTIVATOR
      <% else %>
      <%=  x.status  %>
      <%= ((Time.now - @conversation.last.messages.last.created_at) / 1.minute).round rescue "-" %>
      <% end %>
    </span>
  </td>

  <td class="txt-oflo"><a href="<%= conversation_path(x.id) %>" class="btn btn-primary">Lihat</a></td>
</tr>
<% end %>

app/views/dashboard/_list_msgbox.html.erb
<% MessageBox.where(status: "init").where.not(problem_category_id:nil).each do |x| %>
<tr>
  <td class="txt-oflo"><%= x.user.full_name %></td>
  <td class="txt-oflo"><%= x.created_at.strftime('%d-%m-%Y %T ') %></td>
  <td class="txt-oflo"><%= x.problem_category.name rescue"x" %></td>
  <td class="txt-oflo"><a href="<%= message_box_path(x.id) %>" class="btn btn-primary">Lihat</a></td>
</tr>

<% end %>

app/views/dashboard/_list_notif.html.erb
<% if MessageBox.where(status: "init").where.not(problem_category_id:nil).count >= 1 %>
<script type="text/javascript">
  toastr.info('Ada Box Uneg Uneg belum di buka', 'Box Uneg Uneg', {timeOut: 3000})
  toastr.options = {
    "closeButton": true,
    "debug": false,
    "newestOnTop": true,
    "progressBar": false,
    "positionClass": "toast-bottom-right",
    "preventDuplicates": 1,
    "onclick": null,
     "maxOpened": 1,
    "showDuration": "2000",
    "hideDuration": "2000",
    "timeOut": "2000",
    "extendedTimeOut": "1000",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "fadeIn",
    "hideMethod": "fadeOut"
  };

</script>

<% end %>
<% if Conversation.where(status: "init").where.not(problem_category_id:nil).count >= 1 %>
<script type="text/javascript">
  toastr.warning('Ada Chat belum db assign', 'Chat', {timeOut: 3000})
  toastr.options = {
    "closeButton": true,
    "debug": false,
    "newestOnTop": true,
    "progressBar": false,
    "positionClass": "toast-bottom-right",
    "preventDuplicates": 1,
    "onclick": null,
     "maxOpened": 1,
    "showDuration": "2000",
    "hideDuration": "2000",
    "timeOut": "2000",
    "extendedTimeOut": "1000",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "fadeIn",
    "hideMethod": "fadeOut"
  };

</script>
<% end %>
<audio autoplay loop>
  <source src="<%= asset_url('eventually.mp3') %>" type="audio/mpeg">
  Your browser does not support the audio element.
</audio>

app/views/dashboard/faq.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="p-3 shadow" style="overflow-y:scroll">
          <div class="d-block mb-3">
            <div class="my-1">
              <h3><strong>Gimana caranya curhat di Hallo Arif ?</strong></h3>

<p>Atas izin dan pertolongan Sang Maha Pencipta. Hallo Arif akan membuka pelayanan Secara online kalian bisa download aplikasi Hallo Arif melalui playstore dan silahkan memilih produk yang kalian sukai.&nbsp;</p>

<h3><strong>Kapan nih kita bisa curhat di Hallo Arif ?</strong></h3>

<p>Atas izin dan pertolongan Sang Maha Pencipta. Hallo Arif &nbsp;memiliki jam oprasional layanan motivasi di jam 07.00 &ndash; 22.00 &nbsp;WIB dan kedepanya akan menerima curhatan kalian 24 jam ! keren kannn ? keren doong.<br />
Siapa aja sih yang bisa menggunakan aplikasi di Hallo Arif ?<br />
Siapa saja berhak untuk mendapat motivasi, siapa saja berhak untuk di dengar keluh kesah nya, siapa saja berhak untuk mempunyai hidup yang lebih baik, dan siapa saja berhak untuh mendekatkan diri kepada Sang Maha Pencipta. Untuk menyelesaikan semua masalah nya. So, Hallo Arif tidak mengenal usia, jabatan, jenis kelamin, dll. Kami siap menerima dan menampung semua keluh kesah serta siap memberikan motivator ke semua orang.</p>

<h3><br />
<strong>Seberapa lama kita bisa curhat ?</strong></h3>

<p>Hallo Arif memberikan waktu untuk klien curhat melalui telpon maksimal 30 menit untuk setiap sesi curhat. Tapi kalau belum puas dan mau nambah lagi, nanti motivatornya akan bertanya langsung ke klien yang masih ingin curhat.</p>

<h3><br />
<strong>Seberapa sering kita bisa curhat ?</strong></h3>

<p>Kamu boleh dan bisa curhat kapanpun, dimanapun dan sesuai dengan kebutuhan motivasi yang dibutuhkan. Karena di Hallo Arif ada Box Uneg-Uneg yang bisa menampung semua curhatan mu.&nbsp;</p>

<h3><strong>Bayar ga sih ?</strong></h3>

<p>Curhat by phone dan chat pihak Hallo Arif memberikan biaya namun biaya yang dikeluarkan masih terjangkau selain itu yang didapatkan klien Hallo Arif atas ijin Sang Maha Pencipta mendapatkan hal lain yang juga bermanfaat.</p>

<h3><strong>Gimana sih caranya daftar jadi client Hallo Arif ?&nbsp;</strong></h3>

<p>Kalian bisa download langsung aplikasi Hallo Arif, kemudia pilih <a href="https://halloarif.id/register"><u>sign up/daftar</u></a>&nbsp;dan isi kolom yang tertera ya..<br />
&nbsp;</p>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>