config/routes.rb
Rails.application.routes.draw do

  resources :videos
  resources :biodata
  resources :notification_data
  resources :testimonies
  resources :detail_motivators
  resources :schedules
  mount Ckeditor::Engine => '/ckeditor'
  get 'dashboard/index'
  get 'dashboard' => "dashboard#index", as: :dashboard
  get 'dashboard/partial_conver'
  get 'dashboard/partial_msgbox'
  get 'dashboard/partial_notif'
  get 'users/message_box'
  get 'messages/partial_conver'
  get 'pages/partial_conver'
  resources :messages


  root 'pages#index'

  resources :packages
  resources :conversations
  resources :before_conversation
  resources :before_box
  resources :after_register
  resources :promos
  resources :articles
  resources :article_categories, path: "kategori"
  resources :quotes
  resources :images
  resources :sliders
  resources :message_boxes
  resources :problem_categories
  resources :users
  get '/answer' => "pages#answer", as: :answer
  get '/answer-chat' => "pages#answer_chat", as: :answer_chat
  get '/rate-box' => "pages#rate_box", as: :rate_box
  get '/list_box' => "pages#list_box", as: :list_box
  get '/list_chat' => "pages#list_chat", as: :list_chat
  get '/user_agrement' => "pages#user_agrement", as: :user_agrement
  get '/intro' => "pages#intro", as: :intro
  get '/questioner' => "pages#questioner", as: :questioner
  get '/code-of-conduct' => "pages#conduct", as: :conduct
  get '/setup-payment' => "payments#init_payment", as: :init_payment
  get '/detail-payment' => "pages#payment", as: :payment_detail
  get '/beli-paket' => "conversations#init_conversation", as: :init_conversation
  get '/finish' => "conversations#finish", as: :finish
  get '/list-paket' => "pages#list_package", as: :list_package
  get '/about' => "pages#about", as: :about
  get '/contact' => "pages#contact", as: :contact
  get '/history' => "pages#history", as: :history
  get '/history-mtv' => "pages#history_mtv", as: :history_mtv
  get 'list-province' =>  "shared#province"
  get 'list-city' =>  "shared#city"
  get 'list-category' =>  "shared#problem_category"
  get 'validate_promo_code' => "payments#validate_promo_code"
  get '/payment-success' => "payments#payment_success"
  get '/payment-pending' => "payments#payment_pending"
  get '/payment-error' => "payments#payment_error"
  get 'init_box' => "message_boxes#init_box", as: :init_box
  get 'finish_box' => "pages#finish", as: :finish_message_box
  get 'info-motivator' => "pages#mtv_info", as: :mtv_info
  post 'payments/notify'

  get "/faq" => "dashboard#faq", :as => :faq
  get "/semua-artikel" => "pages#allstory", :as => :allstory
  post "/sendkeys" => "message_boxes#getJSON", :as => :getJSON
   post "/sendNo" => "message_boxes#sendPush", :as => :sendPush
  resources :payments
  devise_for :users ,
   path: '',
   path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, :controllers => { :sessions => "sessions" }

   namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        delete "log_out", to: "sessions#destroy"
      end
        put "update_identity", to: "users#update_identity"
        resources :message_boxes
        put "add_rating/:id", to: "message_boxes#create_rating"
    end
  end
end

app/models/promo.rb
class Promo < ApplicationRecord
  Type = ['promo-code' , 'referral-code']
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'admin'
  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(promo_params)

    respond_to do |format|
      if @promo.save
        format.html { redirect_to @promo, notice: 'Promo was successfully created.' }
        format.json { render :show, status: :created, location: @promo }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to promos_url, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:name, :description, :promo_type, :code, :limit,:status, :discount, :start_date, :end_date)
    end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<%= form_for @promo, :html => { :class => "form-horizontal promo" } do |f| %>

  <% if @promo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@promo.errors.count, "error") %> prohibited this promo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @promo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :code, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :code, :class => 'form-control' %>
    </div>
    <%=f.error_span(:code) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control', row: 5 %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :discount,'Discount %', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :discount, :class => 'form-control' %>
    </div>
    <%=f.error_span(:discount) %>
  </div>
  <div class="form-group">
    <%= f.label :limit, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :limit, :class => 'form-control' %>
    </div>
    <%=f.error_span(:limit) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <div class="custom-control custom-switch">

        <!-- Default checked -->
      <div class="custom-control custom-switch">
        <%= f.check_box :status , class: "custom-control-input"%>
        <label class="custom-control-label" for="promo_status">Aktif</label>
      </div>
      </div>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :promo_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :promo_type, Promo::Type.map {|c| [c.to_s.titleize, c] },{},{:class=>"w-100 form-control select2"}%>
    </div>
    <%=f.error_span(:promo_type) %>
  </div>
  <div class="form-group">
    <div class="row mb-3">
      <div class="col">
        <%= f.date_field :start_date, :class => 'form-control' %>
      </div>
      <div class="col">
        <%= f.date_field :end_date, :class => 'form-control' %>
      </div>
    </div>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                promos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>



<script type="text/javascript">
  $("input[type=date]").datepicker({
  dateFormat: 'yy-mm-dd',
  onSelect: function(dateText, inst) {
    $(inst).val(dateText); // Write the value in the input
  }
});

// Code below to avoid the classic date-picker

</script>

app/views/promos/edit.html.erb
<%- model_class = Promo -%>
<div class="card">
  <div class="card-body">
    <div class="page-header">
      <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
    </div>
    <%= render :partial => 'form' %>
  </div>
</div>

app/views/promos/index.html.erb
<%- model_class = Promo -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">

    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_index_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h1 class="page-title">Kode Promo</h1>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:name) %></th>
                <th><%= model_class.human_attribute_name(:code) %></th>
                <th><%= model_class.human_attribute_name(:limit) %></th>
                <th>Total User</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @promos.each do |promo| %>
              <tr>
                <td><%= link_to promo.id, promo_path(promo) %></td>
                <td><%= promo.name %></td>
                <td><%= promo.code %></td>
                <td><%= promo.limit %></td>
                <td><%= User.where(signup_referral_code: promo.code).count + Payment.where(promo_code: promo.code).count %></td>
                <td><%=promo.start_date.strftime("%e %B %Y  %T ") rescue "" %></td>
                <td><%=promo.end_date.strftime("%e %B %Y  %T ") rescue "" %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  promo_path(promo), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_promo_path(promo), :class => 'btn btn-default btn-xs' %>
                  <%# link_to t('.destroy', :default => t("helpers.links.destroy")),
                  promo_path(promo),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <%= link_to t('.new', :default => t("helpers.links.new")),
  new_promo_path,
  :class => 'btn btn-primary' %>

app/views/promos/new.html.erb
<%- model_class = Promo -%>
<div class="card">
  <div class="card-body">
    <div class="page-header">
      <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
    </div>
    <%= render :partial => 'form' %>
  </div>
</div>

app/views/promos/show.html.erb
<div class="card">
  <div class="card-body">
    <%- model_class = Promo -%>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
    </div>

    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @promo.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
      <dd><%= @promo.description %></dd>
      <dt><strong><%= model_class.human_attribute_name(:discount) %>:</strong></dt>
      <dd><%= @promo.discount %></dd>
      <dt><strong><%= model_class.human_attribute_name(:limit ) %>:</strong></dt>
      <dd><%= @promo.limit %></dd>
    </dl>
    <h1>Pengguna Promo</h1>
    <% if @promo.promo_type == 'promo-code' %>
    <table  class="table table-striped">
      <thead>
        <tr>
          <th>User</th>
          <th>Package</th>
          <th>Tanggal</th>
        </tr>
      </thead>

      <tbody>
        <% Payment.where(promo_code: @promo.code).each do |payment| %>
          <tr>
            <td><%= payment.user.full_name rescue "" %></td>
            <td><%= payment.package.name rescue "" %></td>
            <td><%= payment.created_at rescue "" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <h3>User Register With this Code</h3>
    <ul>
      <% User.where(signup_referral_code: @promo.code).each do |x| %>
      <li> <a href="#"> <%= x.full_name %> - <%= x.email %> </a></li>
      <% end %>
    </ul>

    <% end %>
  </div>
</div>