config/routes.rb
Rails.application.routes.draw do

  resources :videos
  resources :biodata
  resources :notification_data
  resources :testimonies
  resources :detail_motivators
  resources :schedules
  mount Ckeditor::Engine => '/ckeditor'
  get 'dashboard/index'
  get 'dashboard' => "dashboard#index", as: :dashboard
  get 'dashboard/partial_conver'
  get 'dashboard/partial_msgbox'
  get 'dashboard/partial_notif'
  get 'users/message_box'
  get 'messages/partial_conver'
  get 'pages/partial_conver'
  resources :messages


  root 'pages#index'

  resources :packages
  resources :conversations
  resources :before_conversation
  resources :before_box
  resources :after_register
  resources :promos
  resources :articles
  resources :article_categories, path: "kategori"
  resources :quotes
  resources :images
  resources :sliders
  resources :message_boxes
  resources :problem_categories
  resources :users
  get '/answer' => "pages#answer", as: :answer
  get '/answer-chat' => "pages#answer_chat", as: :answer_chat
  get '/rate-box' => "pages#rate_box", as: :rate_box
  get '/list_box' => "pages#list_box", as: :list_box
  get '/list_chat' => "pages#list_chat", as: :list_chat
  get '/user_agrement' => "pages#user_agrement", as: :user_agrement
  get '/intro' => "pages#intro", as: :intro
  get '/questioner' => "pages#questioner", as: :questioner
  get '/code-of-conduct' => "pages#conduct", as: :conduct
  get '/setup-payment' => "payments#init_payment", as: :init_payment
  get '/detail-payment' => "pages#payment", as: :payment_detail
  get '/beli-paket' => "conversations#init_conversation", as: :init_conversation
  get '/finish' => "conversations#finish", as: :finish
  get '/list-paket' => "pages#list_package", as: :list_package
  get '/about' => "pages#about", as: :about
  get '/contact' => "pages#contact", as: :contact
  get '/history' => "pages#history", as: :history
  get '/history-mtv' => "pages#history_mtv", as: :history_mtv
  get 'list-province' =>  "shared#province"
  get 'list-city' =>  "shared#city"
  get 'list-category' =>  "shared#problem_category"
  get 'validate_promo_code' => "payments#validate_promo_code"
  get '/payment-success' => "payments#payment_success"
  get '/payment-pending' => "payments#payment_pending"
  get '/payment-error' => "payments#payment_error"
  get 'init_box' => "message_boxes#init_box", as: :init_box
  get 'finish_box' => "pages#finish", as: :finish_message_box
  get 'info-motivator' => "pages#mtv_info", as: :mtv_info
  post 'payments/notify'

  get "/faq" => "dashboard#faq", :as => :faq
  get "/semua-artikel" => "pages#allstory", :as => :allstory
  post "/sendkeys" => "message_boxes#getJSON", :as => :getJSON
   post "/sendNo" => "message_boxes#sendPush", :as => :sendPush
  resources :payments
  devise_for :users ,
   path: '',
   path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, :controllers => { :sessions => "sessions" }

   namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        delete "log_out", to: "sessions#destroy"
      end
        put "update_identity", to: "users#update_identity"
        resources :message_boxes
        put "add_rating/:id", to: "message_boxes#create_rating"
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :user
    belongs_to :package
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html {
        c = Conversation.new
        c.user_id =  current_user.id
        c.package_id = @payment.package_id
        c.status = "init"
        c.save(validate: false)
        redirect_to before_conversation_path(:question_1), notice: 'Paket Berhasil di Aktifkan !' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def validate_promo_code
    if Promo.where(promo_type: "promo-code").where(code: params[:promo_code].upcase).exists?
      promo = Promo.where(code: params[:promo_code].upcase).last
      if promo.end_date < Date.today
        redirect_back(fallback_location: root_path, alert: "Promo telah berakhir")
      else
        payment = Payment.find(params[:payment_id])
        payment.update_attribute(:promo_code, promo.code)
        if promo.discount.to_i == 100
          c = Conversation.new
          c.user_id =  current_user.id
          c.package_id = payment.package_id
          c.status = "init"
          c.save(validate: false)
          redirect_to before_conversation_path(:question_1), notice: 'Paket Berhasil di Aktifkan !'
        else
          redirect_back(fallback_location: root_path, notice: "Kode Promo berhasil")
        end
      end
      else
        redirect_back(fallback_location: root_path, alert: "Kode Promo Tidak Ditemukan")
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def init_payment
    c = Payment.new
    c.user_id =  current_user.id
    c.package_id = params[:packages_id]
    c.status = "init"
    c.save(validate: false)
    # redirect_to before_conversation_path(:question_1)
    redirect_to payment_detail_path(payment: c.id)
  end

  def notify
    Payment.find(params["order_id"]).update_attribute(
      :status, params["transaction_status"]
    )

    x = Payment.find(params["order_id"])
    if x.status == "settlement"
      c = Conversation.new
      c.user_id =  x.user_id
      c.package_id = x.package_id
      c.status = "init"
      c.save(validate: false)
    end


    # must return status 200
    render text: "ACK"
  end

  def payment_success

  end

  def payment_pending

  end

  def payment_error

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:user_id, :package_id, :promo_id, :status, :promo_code)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :payment_user_id %>
  </div>

  <div class="field">
    <%= form.label :package_id %>
    <%= form.text_field :package_id, id: :payment_package_id %>
  </div>

  <div class="field">
    <%= form.label :promo_id %>
    <%= form.text_field :promo_id, id: :payment_promo_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :payment_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Package</th>
      <th>Promo</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.user_id %></td>
        <td><%= payment.package_id %></td>
        <td><%= payment.promo_id %></td>
        <td><%= payment.status %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/payment_success.html.erb
<section>
  <div class="container">
    <div class="text-center">
      <h1>Pembayaran Berhasil</h1>
      <a href="<%= before_conversation_path(:question_1) %>" class="btn btn-primary">Mulai Chat Motivasi</a>
    </div>
  </div>
</section>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @payment.user_id %>
</p>

<p>
  <strong>Package:</strong>
  <%= @payment.package_id %>
</p>

<p>
  <strong>Promo:</strong>
  <%= @payment.promo_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment.status %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>