config/routes.rb
Rails.application.routes.draw do

  resources :videos
  resources :biodata
  resources :notification_data
  resources :testimonies
  resources :detail_motivators
  resources :schedules
  mount Ckeditor::Engine => '/ckeditor'
  get 'dashboard/index'
  get 'dashboard' => "dashboard#index", as: :dashboard
  get 'dashboard/partial_conver'
  get 'dashboard/partial_msgbox'
  get 'dashboard/partial_notif'
  get 'users/message_box'
  get 'messages/partial_conver'
  get 'pages/partial_conver'
  resources :messages


  root 'pages#index'

  resources :packages
  resources :conversations
  resources :before_conversation
  resources :before_box
  resources :after_register
  resources :promos
  resources :articles
  resources :article_categories, path: "kategori"
  resources :quotes
  resources :images
  resources :sliders
  resources :message_boxes
  resources :problem_categories
  resources :users
  get '/answer' => "pages#answer", as: :answer
  get '/answer-chat' => "pages#answer_chat", as: :answer_chat
  get '/rate-box' => "pages#rate_box", as: :rate_box
  get '/list_box' => "pages#list_box", as: :list_box
  get '/list_chat' => "pages#list_chat", as: :list_chat
  get '/user_agrement' => "pages#user_agrement", as: :user_agrement
  get '/intro' => "pages#intro", as: :intro
  get '/questioner' => "pages#questioner", as: :questioner
  get '/code-of-conduct' => "pages#conduct", as: :conduct
  get '/setup-payment' => "payments#init_payment", as: :init_payment
  get '/detail-payment' => "pages#payment", as: :payment_detail
  get '/beli-paket' => "conversations#init_conversation", as: :init_conversation
  get '/finish' => "conversations#finish", as: :finish
  get '/list-paket' => "pages#list_package", as: :list_package
  get '/about' => "pages#about", as: :about
  get '/contact' => "pages#contact", as: :contact
  get '/history' => "pages#history", as: :history
  get '/history-mtv' => "pages#history_mtv", as: :history_mtv
  get 'list-province' =>  "shared#province"
  get 'list-city' =>  "shared#city"
  get 'list-category' =>  "shared#problem_category"
  get 'validate_promo_code' => "payments#validate_promo_code"
  get '/payment-success' => "payments#payment_success"
  get '/payment-pending' => "payments#payment_pending"
  get '/payment-error' => "payments#payment_error"
  get 'init_box' => "message_boxes#init_box", as: :init_box
  get 'finish_box' => "pages#finish", as: :finish_message_box
  get 'info-motivator' => "pages#mtv_info", as: :mtv_info
  post 'payments/notify'

  get "/faq" => "dashboard#faq", :as => :faq
  get "/semua-artikel" => "pages#allstory", :as => :allstory
  post "/sendkeys" => "message_boxes#getJSON", :as => :getJSON
   post "/sendNo" => "message_boxes#sendPush", :as => :sendPush
  resources :payments
  devise_for :users ,
   path: '',
   path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, :controllers => { :sessions => "sessions" }

   namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        delete "log_out", to: "sessions#destroy"
      end
        put "update_identity", to: "users#update_identity"
        resources :message_boxes
        put "add_rating/:id", to: "message_boxes#create_rating"
    end
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  extend FriendlyId
  friendly_id :name
end

app/controllers/article_categories_controller.rb
class ArticleCategoriesController < ApplicationController
  before_action :set_article_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_user!, except: [:show]
  layout 'admin', except: [:show]
  # GET /article_categories
  # GET /article_categories.json
  def index
    @article_categories = ArticleCategory.all
  end

  # GET /article_categories/1
  # GET /article_categories/1.json
  def show
    @articles = Article.where(article_category_id: @article_category.id).order(created_at: :desc).page(params[:page]).per(6)
  end

  # GET /article_categories/new
  def new
    @article_category = ArticleCategory.new
  end

  # GET /article_categories/1/edit
  def edit
  end

  # POST /article_categories
  # POST /article_categories.json
  def create
    @article_category = ArticleCategory.new(article_category_params)

    respond_to do |format|
      if @article_category.save
        format.html { redirect_to @article_category, notice: 'Article category was successfully created.' }
        format.json { render :show, status: :created, location: @article_category }
      else
        format.html { render :new }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_categories/1
  # PATCH/PUT /article_categories/1.json
  def update
    respond_to do |format|
      if @article_category.update(article_category_params)
        format.html { redirect_to @article_category, notice: 'Article category was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_category }
      else
        format.html { render :edit }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_categories/1
  # DELETE /article_categories/1.json
  def destroy
    @article_category.destroy
    respond_to do |format|
      format.html { redirect_to article_categories_url, notice: 'Article category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_category
      @article_category = ArticleCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_category_params
      params.require(:article_category).permit(:name, :description)
    end
end

app/helpers/article_categories_helper.rb
module ArticleCategoriesHelper
end

app/views/article_categories/_form.html.erb
<%= form_for @article_category, :html => { :class => "form-horizontal article_category" } do |f| %>

  <% if @article_category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@article_category.errors.count, "error") %> prohibited this article_category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @article_category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                article_categories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/article_categories/edit.html.erb
<%- model_class = ArticleCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/article_categories/index.html.erb
<%- model_class = ArticleCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @article_categories.each do |article_category| %>
      <tr>
        <td><%= link_to article_category.id, article_category_path(article_category) %></td>
        <td><%= article_category.name %></td>
        <td><%= article_category.description %></td>
        <td><%= article_category.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      article_category_path(article_category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_article_category_path(article_category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_category_path(article_category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_category_path,
            :class => 'btn btn-primary' %>

app/views/article_categories/new.html.erb
<%- model_class = ArticleCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/article_categories/show.html.erb
<!--articles  -->
<section  style="background-color:#f7f7f7;" id="article">
  <div class="container">
    <div class="text-center mb-5">
      <h2 class="text-warning mb-2"><%= @article_category.name %></h2>
    </div>
    <div class="row">
      <% @articles.each do |x| %>
      <div class="col-md-4 mb-5">
        <div class="card w-100">
          <img class="card-img-top" src="<%= x.image %>" alt="<%= x.title %>">
          <div class="card-body">
            <h5 class="card-title"><%= x.title %></h5>
            <a href="<%= article_path(x.slug) %>" class="btn btn-primary w-100">Selengkapnya</a>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="mt-3">
      <div class="text-center">
          <%= paginate @articles, theme: 'twitter-bootstrap-4' %>
      </div>
    </div>
  </div>
</section>
<!-- articles -->